# Generated by Django 5.1.6 on 2025-03-26 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
